// Generated by gencpp from file PRADA_ems/AddInts.msg
// DO NOT EDIT!


#ifndef PRADA_EMS_MESSAGE_ADDINTS_H
#define PRADA_EMS_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <PRADA_ems/AddIntsRequest.h>
#include <PRADA_ems/AddIntsResponse.h>


namespace PRADA_ems
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace PRADA_ems


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::PRADA_ems::AddInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::PRADA_ems::AddInts&) { return value(); }
};

template<>
struct DataType< ::PRADA_ems::AddInts > {
  static const char* value()
  {
    return "PRADA_ems/AddInts";
  }

  static const char* value(const ::PRADA_ems::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::PRADA_ems::AddIntsRequest> should match
// service_traits::MD5Sum< ::PRADA_ems::AddInts >
template<>
struct MD5Sum< ::PRADA_ems::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::PRADA_ems::AddInts >::value();
  }
  static const char* value(const ::PRADA_ems::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::PRADA_ems::AddIntsRequest> should match
// service_traits::DataType< ::PRADA_ems::AddInts >
template<>
struct DataType< ::PRADA_ems::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::PRADA_ems::AddInts >::value();
  }
  static const char* value(const ::PRADA_ems::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::PRADA_ems::AddIntsResponse> should match
// service_traits::MD5Sum< ::PRADA_ems::AddInts >
template<>
struct MD5Sum< ::PRADA_ems::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::PRADA_ems::AddInts >::value();
  }
  static const char* value(const ::PRADA_ems::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::PRADA_ems::AddIntsResponse> should match
// service_traits::DataType< ::PRADA_ems::AddInts >
template<>
struct DataType< ::PRADA_ems::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::PRADA_ems::AddInts >::value();
  }
  static const char* value(const ::PRADA_ems::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRADA_EMS_MESSAGE_ADDINTS_H
